<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>disable</Nullable>
    <RootNamespace>Habagat.Verify</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HabagatSim\HabagatSim.csproj" />
  </ItemGroup>

</Project>
